[pytest]
addopts = -v --tb=short
base_url = https://restful-booker.herokuapp.com
markers =
    positive_test: mark test as positive test.
    negative_test: mark test as negative test.
log_cli = true
log_cli_level = INFO
