[pytest]
addopts = -ra --headed
markers =
    login: mark test as a login test.
    adding_to_cart: mark test as add to cart test.
    checkout: mark test as checkout test.
    slow: mark test as slow.
log_cli = true
log_cli_level = INFO
log_cli_format = %(asctime)s - %(levelname)s - %(name)s.%(funcName)s: %(message)s
log_cli_date_format = %Y-%m-%d %H:%M:%S
